adding pages and routing
misalazeem/Math-Magicians pull request #5
Opened 2023-06-06 22:48 UTC by misalazeem

- Added Pages
- Added Routing
- Made website responsive for mobile
- Added mobile hamburger

2023-06-06 23:26 UTC, Munsa1 requested changes
Hi @misalazeem, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Nice UI Design :heavy_check_mark: 
Used React Router Dom For Routing Pages :heavy_check_mark: 
Descriptive PR :heavy_check_mark: 
Responsive Web Design :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-06 23:26 UTC, Munsa1 commented on src/components/Home.jsx
> +  );
- [ ] Great job creating the home page, however, our design has to follow the given wireframe. Kindly adjust the `Welcome to our page `  heading to match the given layout

Your design
![image](https://github.com/misalazeem/Math-Magicians/assets/81932478/1be979cd-5629-4c04-bbcf-ee1c5abf1aa2)

Given wireframe
![image](https://github.com/misalazeem/Math-Magicians/assets/81932478/a9bc8fb8-c07a-462b-aff4-4ef560fca54e)

Kindly align the heading to the left as is in the given design

2023-06-06 23:26 UTC, Munsa1 commented on src/components/calculator.jsx
>          </div>
- [ ] Again here kindly align the calculator UI so as to match the given wireframe. Notice how the calculator UI aligns with the `links` at the top to the right.

Your design
![image](https://github.com/misalazeem/Math-Magicians/assets/81932478/9ff07fa7-02aa-48d8-98f4-81f508147ba4)

Given wireframe
![image](https://github.com/misalazeem/Math-Magicians/assets/81932478/89a96ef1-5678-43b4-92a1-824f5b8e6310)

2023-06-07 00:00 UTC, OyePriscilla approved these changes
Hi @misalazeem 👏, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
Designed app according to the given wireframe ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 07:06 UTC, merged